services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
      - qdrant
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - QDRANT_HOST=http://qdrant:6333
    volumes:
      - ./bot:/app  # Mount the entire bot directory to /app in the container
    networks:
      - rag_bgg_rag_network
    deploy:
      resources:
        limits:
          memory: 12G  # Set memory limit for the streamlit service

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro  # Mount the initialization script as read-only
    networks:
      - rag_bgg_rag_network
    deploy:
      resources:
        limits:
          memory: 1G  # Set memory limit for the mongodb service

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_bgg_rag_network
    deploy:
      resources:
        limits:
          memory: 2G  # Set memory limit for the qdrant service

networks:
  rag_bgg_rag_network:
    external: true

volumes:
  mongo_data:
  qdrant_data: