services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
      - qdrant
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - QDRANT_HOST=http://qdrant:6333

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data: